name: ruumi_listing
description: "RUUMI Property Listing App - Technical Test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP Client
  dio: ^5.4.3

  # Local Storage
  shared_preferences: ^2.2.3

  # Navigation
  go_router: ^14.2.0

  # UI
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
